CREATE OR REPLACE TRIGGER consumibles_sub
AFTER 
    INSERT ON CONSUMIBLES
FOR EACH ROW
BEGIN
    if(:NEW.TIPO='Menu') then
        INSERT INTO MENUS VALUES(:NEW.ID_CONSUMIBLE);
    elsif(:NEW.TIPO='Plato') then
        INSERT INTO PLATOS VALUES(:NEW.ID_CONSUMIBLE);
    else
        INSERT INTO BEBIDAS VALUES(:NEW.ID_CONSUMIBLE,0);
    end if;
END;
/
CREATE OR REPLACE TRIGGER pedidos_metadata
BEFORE
    INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
    UPDATE PEDIDOS SET ID_camarero=(SELECT ID_EMPLEADO FROM EMPLEADOS WHERE USERNAME=user),FECHA_CREACION=SYSDATE WHERE ID_PEDIDO=:NEW.ID_PEDIDO;
END;
